version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run unit tests
          command: pytest tests/

  docker-build:
    docker:
      - image: docker:20.10.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/invoicer:latest .
      - run:
          name: Login to Docker Hub
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker image to Docker Hub
          command: docker push $DOCKERHUB_USERNAME/invoicer:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - docker-build:
          requires:
            - build
